# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservice_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'microservice_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amicroservice_manager.proto\x12\x14microservice_manager\"\x0f\n\rMaxRepRequest\"\"\n\x0eMaxRepResponse\x12\x10\n\x08max_reps\x18\x01 \x01(\x05\"\x92\x01\n\x0b\x41RMDecision\x12\x19\n\x11microservice_name\x18\x01 \x01(\t\x12\x1e\n\x16\x61llowed_scaling_action\x18\x02 \x01(\t\x12\x15\n\rfeasible_reps\x18\x03 \x01(\x05\x12\x14\n\x0c\x61rm_max_reps\x18\x04 \x01(\x05\x12\x1b\n\x13\x63pu_request_per_rep\x18\x05 \x01(\x05\"\x1f\n\rScalingStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x15\n\x13ResourceDataRequest\"\xaa\x02\n\x0cResourceData\x12\x19\n\x11microservice_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_reps\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x65sired_reps\x18\x03 \x01(\x05\x12\x19\n\x11\x63pu_usage_per_rep\x18\x04 \x01(\x05\x12\x1b\n\x13\x63pu_request_per_rep\x18\x05 \x01(\x05\x12\x1f\n\x17\x63pu_utilization_per_rep\x18\x06 \x01(\x05\x12\x1e\n\x16\x64\x65sired_for_scale_reps\x18\x07 \x01(\x05\x12\x16\n\x0escaling_action\x18\x08 \x01(\t\x12\x10\n\x08max_reps\x18\t \x01(\x05\x12\x10\n\x08min_reps\x18\n \x01(\x05\x12\x1e\n\x16target_cpu_utilization\x18\x0b \x01(\x05\x32\xb4\x02\n\x13MicroserviceManager\x12\x66\n\x13\x45xtractResourceData\x12).microservice_manager.ResourceDataRequest\x1a\".microservice_manager.ResourceData\"\x00\x12Z\n\x0e\x45xecuteScaling\x12!.microservice_manager.ARMDecision\x1a#.microservice_manager.ScalingStatus\"\x00\x12Y\n\nGetMaxReps\x12#.microservice_manager.MaxRepRequest\x1a$.microservice_manager.MaxRepResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservice_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAXREPREQUEST']._serialized_start=52
  _globals['_MAXREPREQUEST']._serialized_end=67
  _globals['_MAXREPRESPONSE']._serialized_start=69
  _globals['_MAXREPRESPONSE']._serialized_end=103
  _globals['_ARMDECISION']._serialized_start=106
  _globals['_ARMDECISION']._serialized_end=252
  _globals['_SCALINGSTATUS']._serialized_start=254
  _globals['_SCALINGSTATUS']._serialized_end=285
  _globals['_RESOURCEDATAREQUEST']._serialized_start=287
  _globals['_RESOURCEDATAREQUEST']._serialized_end=308
  _globals['_RESOURCEDATA']._serialized_start=311
  _globals['_RESOURCEDATA']._serialized_end=609
  _globals['_MICROSERVICEMANAGER']._serialized_start=612
  _globals['_MICROSERVICEMANAGER']._serialized_end=920
# @@protoc_insertion_point(module_scope)
