# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adaptive_resource_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'adaptive_resource_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61\x64\x61ptive_resource_manager.proto\x12\x19\x61\x64\x61ptive_resource_manager\"\xaa\x02\n\x0cResourceData\x12\x19\n\x11microservice_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_reps\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x65sired_reps\x18\x03 \x01(\x05\x12\x19\n\x11\x63pu_usage_per_rep\x18\x04 \x01(\x05\x12\x1b\n\x13\x63pu_request_per_rep\x18\x05 \x01(\x05\x12\x1f\n\x17\x63pu_utilization_per_rep\x18\x06 \x01(\x05\x12\x1e\n\x16\x64\x65sired_for_scale_reps\x18\x07 \x01(\x05\x12\x16\n\x0escaling_action\x18\x08 \x01(\t\x12\x10\n\x08max_reps\x18\t \x01(\x05\x12\x10\n\x08min_reps\x18\n \x01(\x05\x12\x1e\n\x16target_cpu_utilization\x18\x0b \x01(\x05\"W\n\x10ResourceDataList\x12\x43\n\x12microservices_data\x18\x01 \x03(\x0b\x32\'.adaptive_resource_manager.ResourceData\"\x92\x01\n\x0b\x41RMDecision\x12\x19\n\x11microservice_name\x18\x01 \x01(\t\x12\x1e\n\x16\x61llowed_scaling_action\x18\x02 \x01(\t\x12\x15\n\rfeasible_reps\x18\x03 \x01(\x05\x12\x14\n\x0c\x61rm_max_reps\x18\x04 \x01(\x05\x12\x1b\n\x13\x63pu_request_per_rep\x18\x05 \x01(\x05\"W\n\x0f\x41RMDecisionList\x12\x44\n\x14scaling_instructions\x18\x01 \x03(\x0b\x32&.adaptive_resource_manager.ARMDecision2\x88\x01\n\x17\x41\x64\x61ptiveResourceManager\x12m\n\x10ResourceExchange\x12+.adaptive_resource_manager.ResourceDataList\x1a*.adaptive_resource_manager.ARMDecisionList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adaptive_resource_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEDATA']._serialized_start=63
  _globals['_RESOURCEDATA']._serialized_end=361
  _globals['_RESOURCEDATALIST']._serialized_start=363
  _globals['_RESOURCEDATALIST']._serialized_end=450
  _globals['_ARMDECISION']._serialized_start=453
  _globals['_ARMDECISION']._serialized_end=599
  _globals['_ARMDECISIONLIST']._serialized_start=601
  _globals['_ARMDECISIONLIST']._serialized_end=688
  _globals['_ADAPTIVERESOURCEMANAGER']._serialized_start=691
  _globals['_ADAPTIVERESOURCEMANAGER']._serialized_end=827
# @@protoc_insertion_point(module_scope)
