# microservice managers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-capacity-analyzer  # deployment name
  labels:
    app: smart-hpa  # get all deployments of smart-hpa.
                    # by kubectl get deployments -l app=smart-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-capacity-analyzer  #TODO
  template:
    metadata:
      labels:
        app: microservice-capacity-analyzer  #TODO
    spec:
      serviceAccount: god
      serviceAccountName: god
      containers:
      - name: microservice-capacity-analyzer-container #TODO
        image: acemarco/microservice-capacity-analyzer:latest
        ports:  # container port exposed
        - containerPort: 8080
        resources:
          requests:
            cpu: 150m
            memory: 100Mi

